name: Gradr

on:
  pull_request:
    branches:
    - master

jobs:
  lint: 
    name: audit code style
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        
    - name: Run Audits
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  ch-1:
    needs: lint
    name: audit challenge 1
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]
        python-version: [3.7]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Deps
      run: |
        pip install requests pytest pytest-json
        pip install --editable .
        yarn install
        yarn remove jest 
        yarn add jest axios xml2json @babel/core @babel/preset-env babel-jest @actions/core @actions/github
        cd pytest-runner && yarn install && cd -
    
    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-py
        path: audits

    - name: Run Audits
      run: |
        yarn jest audits/ch-1 --json --outputFile=audits/ch-1.json --noStackTrace

    - name: Report Audits
      uses: BuildforSDG-Cohort1-Assessment/jest-out@v1
      with:
        challenge: ch-1
        lang: python
      if: always()
  
  ch-2:
    needs: ch-1
    name: audit challenge 2
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]
        python-version: [3.7]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Deps
      run: |
        pip install requests pytest pytest-json
        pip install --editable .
        yarn install
        yarn remove jest 
        yarn add jest axios xml2json @babel/core @babel/preset-env babel-jest @actions/core @actions/github
        cd pytest-runner && yarn install && cd -
    
    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-py
        path: audits

    - name: Run Audits
      run: yarn jest audits/ch-2 --json --outputFile=audits/ch-2.json --noStackTrace

    - name: Report Audits
      uses: BuildforSDG-Cohort1-Assessment/jest-out@v1
      with:
        challenge: ch-2
        lang: python
      if: always()

  ch-3:
    needs: ch-2
    name: audit challenge 3
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]
        python-version: [3.7]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Deps
      run: |
        pip install requests pytest pytest-json
        pip install --editable .
        yarn install
        yarn remove jest 
        yarn add jest axios xml2json @babel/core @babel/preset-env babel-jest @actions/core @actions/github
        cd pytest-runner && yarn install && cd -
    
    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-py
        path: audits

    - name: Run Audits
      run: yarn jest audits/ch-3 --json --outputFile=audits/ch-3.json --noStackTrace

    - name: Report Audits
      uses: BuildforSDG-Cohort1-Assessment/jest-out@v1
      with:
        challenge: ch-3
        lang: python
      if: always()
 
  lighthouse:
    needs: ch-3
    name: audit frontend app (lighthouse)
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: yarn add axios properties-reader @lhci/cli@0.3.x @actions/core @actions/github

    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-js
        path: audits
    
    - name: Injest Frontend App URL
      id: props
      uses: chalu/properties-io@v1
      with:
        file: ./app.properties
        read-from: frontend.url
    
    - name: Run Audits
      run: npx lhci autorun --collect.url=${{ steps.props.outputs.value }} --config=./audits/lighthouserc.json
    
    - name: Report Audits
      uses: BuildforSDG-Cohort1-Assessment/lighthouse-out@v1
      if: always()
  
  ch-4:
    needs: lighthouse
    name: audit frontend UI
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: yarn add jest axios on-covid-19 properties-reader xml2json puppeteer @babel/core @babel/preset-env babel-jest @actions/core @actions/github

    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-js
        path: audits

    - name: Run Audits
      run: npx jest --config=audits/jest.config.js audits/ch-4 --json --outputFile=audits/ch-4.json --noStackTrace

    - name: Report Audits
      uses: BuildforSDG-Cohort1-Assessment/jest-out@v1
      with:
        challenge: ch-4
        lang: javascript
      if: always()

  ch-5:
    needs: ch-3
    name: audit backend API
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: yarn add jest axios on-covid-19 properties-reader xml2json @babel/core @babel/preset-env babel-jest @actions/core @actions/github

    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-js
        path: audits

    - name: Run Audits
      run: npx jest --config=audits/jest.config.js audits/ch-5 --json --outputFile=audits/ch-5.json --noStackTrace

    - name: Report Audits
      uses: BuildforSDG-Cohort1-Assessment/jest-out@v1
      with:
        challenge: ch-5
        lang: javascript
      if: always()
